// Generated by scripts/fetch.js — do not edit by hand.
window.RACE_DATA = {
  "generatedAt": "2026-09-05T00:35:51.532Z",
  "demo": false,
  "title": "KCC Grand Prix",
  "subtitle": "Merged PRs, closed issues and reviews — as a race",
  "period": {
    "since": "2026-09-01",
    "until": "2026-09-30"
  },
  "scope": {
    "orgs": [
      "GoogleCloudPlatform"
    ],
    "repos": [
      "k8s-config-connector"
    ]
  },
  "scoring": {
    "mergedPR": 2,
    "issueClosed": 4,
    "reviewSubmitted": 1
  },
  "cars": {
    "f1": {
      "label": "Formula",
      "speed": 2
    },
    "supercar": {
      "label": "Supercar",
      "speed": 2
    },
    "sports": {
      "label": "Sports",
      "speed": 2
    },
    "muscle": {
      "label": "Muscle",
      "speed": 1
    },
    "hatchback": {
      "label": "Hot hatch",
      "speed": 1
    },
    "pickup": {
      "label": "Pickup",
      "speed": 1
    },
    "van": {
      "label": "Van",
      "speed": 1
    },
    "tractor": {
      "label": "Tractor",
      "speed": 1
    }
  },
  "days": [
    "2026-09-01",
    "2026-09-02",
    "2026-09-03",
    "2026-09-04",
    "2026-09-05",
    "2026-09-06",
    "2026-09-07",
    "2026-09-08",
    "2026-09-09",
    "2026-09-10",
    "2026-09-11",
    "2026-09-12",
    "2026-09-13",
    "2026-09-14",
    "2026-09-15",
    "2026-09-16",
    "2026-09-17",
    "2026-09-18",
    "2026-09-19",
    "2026-09-20",
    "2026-09-21",
    "2026-09-22",
    "2026-09-23",
    "2026-09-24",
    "2026-09-25",
    "2026-09-26",
    "2026-09-27",
    "2026-09-28",
    "2026-09-29",
    "2026-09-30"
  ],
  "racers": [
    {
      "login": "anfernee",
      "name": "Yongkun",
      "car": "tractor",
      "carLabel": "Tractor",
      "color": "#ff3b6b",
      "speed": 1,
      "totals": {
        "pr": 0,
        "issue": 1,
        "review": 12,
        "points": 16,
        "distance": 16
      },
      "daily": [
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 1,
          "review": 3,
          "points": 7
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 1,
          "points": 1
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 8,
          "points": 8
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        }
      ],
      "events": [
        {
          "type": "issue",
          "day": "2026-09-02",
          "title": "ai:feat: KCC support for AIPlatformCachedContent",
          "url": "https://github.com/GoogleCloudPlatform/k8s-config-connector/issues/11377",
          "repo": "GoogleCloudPlatform/k8s-config-connector",
          "number": 11377
        },
        {
          "type": "review",
          "day": "2026-09-02",
          "title": "docs: Design doc for Resource-Level Actuation Pause and Lifecycle Controls",
          "url": "https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/12657",
          "repo": "GoogleCloudPlatform/k8s-config-connector",
          "number": 12657
        },
        {
          "type": "review",
          "day": "2026-09-02",
          "title": "Greenfield: Implement direct controller, E2E fixtures, and fuzzer for LiveStreamAsset",
          "url": "https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/12507",
          "repo": "GoogleCloudPlatform/k8s-config-connector",
          "number": 12507
        },
        {
          "type": "review",
          "day": "2026-09-02",
          "title": "Greenfield: Implement direct KRM reference and tests for DialogflowKnowledgeBase",
          "url": "https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/12274",
          "repo": "GoogleCloudPlatform/k8s-config-connector",
          "number": 12274
        },
        {
          "type": "review",
          "day": "2026-09-03",
          "title": "Greenfield: Implement direct controller, E2E fixtures, and fuzzer for AssuredWorkloadsWorkload",
          "url": "https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/12440",
          "repo": "GoogleCloudPlatform/k8s-config-connector",
          "number": 12440
        },
        {
          "type": "review",
          "day": "2026-09-04",
          "title": "Revert \"fix(container): default cpu_cfs_quota to true in ContainerNodePool kubeletConfig\"",
          "url": "https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/12778",
          "repo": "GoogleCloudPlatform/k8s-config-connector",
          "number": 12778
        },
        {
          "type": "review",
          "day": "2026-09-04",
          "title": "fix(container): default cpu_cfs_quota to true in ContainerNodePool kubeletConfig",
          "url": "https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/12658",
          "repo": "GoogleCloudPlatform/k8s-config-connector",
          "number": 12658
        },
        {
          "type": "review",
          "day": "2026-09-04",
          "title": "Fix SecretManagerSecret createTime status schema",
          "url": "https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/12612",
          "repo": "GoogleCloudPlatform/k8s-config-connector",
          "number": 12612
        },
        {
          "type": "review",
          "day": "2026-09-04",
          "title": "Fix controller and test for DataprocSession",
          "url": "https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/12495",
          "repo": "GoogleCloudPlatform/k8s-config-connector",
          "number": 12495
        },
        {
          "type": "review",
          "day": "2026-09-04",
          "title": "Support Datastore mode Firestore indexes",
          "url": "https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/12446",
          "repo": "GoogleCloudPlatform/k8s-config-connector",
          "number": 12446
        },
        {
          "type": "review",
          "day": "2026-09-04",
          "title": "fix(bigquerydataset): correct FullID and selfLink conversion for project IDs containing a colon",
          "url": "https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/12383",
          "repo": "GoogleCloudPlatform/k8s-config-connector",
          "number": 12383
        },
        {
          "type": "review",
          "day": "2026-09-04",
          "title": "fix(k8s): preserve location identity fields in trimmed spec with managed fields",
          "url": "https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/12326",
          "repo": "GoogleCloudPlatform/k8s-config-connector",
          "number": 12326
        },
        {
          "type": "review",
          "day": "2026-09-04",
          "title": "ai:chore: Implement direct types for: VMMigrationGroup",
          "url": "https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/11250",
          "repo": "GoogleCloudPlatform/k8s-config-connector",
          "number": 11250
        }
      ]
    },
    {
      "login": "acpana",
      "name": "Alex",
      "car": "tractor",
      "carLabel": "Tractor",
      "color": "#00e0ff",
      "speed": 1,
      "totals": {
        "pr": 1,
        "issue": 1,
        "review": 5,
        "points": 11,
        "distance": 11
      },
      "daily": [
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 3,
          "points": 3
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 1,
          "issue": 1,
          "review": 2,
          "points": 8
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        }
      ],
      "events": [
        {
          "type": "review",
          "day": "2026-09-02",
          "title": "ai:chore: Implement direct types for: VertexAIRagCorpus",
          "url": "https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/11389",
          "repo": "GoogleCloudPlatform/k8s-config-connector",
          "number": 11389
        },
        {
          "type": "review",
          "day": "2026-09-02",
          "title": "Implement direct KRM types and IdentityV2 for CCInsightsAnalysisRule",
          "url": "https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/11169",
          "repo": "GoogleCloudPlatform/k8s-config-connector",
          "number": 11169
        },
        {
          "type": "review",
          "day": "2026-09-02",
          "title": "Support for Vertex AI Discovery Engine Suite",
          "url": "https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/6909",
          "repo": "GoogleCloudPlatform/k8s-config-connector",
          "number": 6909
        },
        {
          "type": "pr",
          "day": "2026-09-04",
          "title": "Fix NotebookInstanceV2 and verify against realGCP",
          "url": "https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/12314",
          "repo": "GoogleCloudPlatform/k8s-config-connector",
          "number": 12314
        },
        {
          "type": "issue",
          "day": "2026-09-04",
          "title": "Vertex AI Workbench KCC Support",
          "url": "https://github.com/GoogleCloudPlatform/k8s-config-connector/issues/7168",
          "repo": "GoogleCloudPlatform/k8s-config-connector",
          "number": 7168
        },
        {
          "type": "review",
          "day": "2026-09-04",
          "title": "Greenfield: Implement direct KRM types, identity, and generate.sh for APIHubCuration",
          "url": "https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/11729",
          "repo": "GoogleCloudPlatform/k8s-config-connector",
          "number": 11729
        },
        {
          "type": "review",
          "day": "2026-09-04",
          "title": "ai:chore: Implement direct types for: VMMigrationGroup",
          "url": "https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/11250",
          "repo": "GoogleCloudPlatform/k8s-config-connector",
          "number": 11250
        }
      ]
    },
    {
      "login": "anhdle-sso",
      "name": "Anh",
      "car": "tractor",
      "carLabel": "Tractor",
      "color": "#ffd23f",
      "speed": 1,
      "totals": {
        "pr": 1,
        "issue": 2,
        "review": 6,
        "points": 16,
        "distance": 16
      },
      "daily": [
        {
          "pr": 1,
          "issue": 0,
          "review": 1,
          "points": 3
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 2,
          "points": 2
        },
        {
          "pr": 0,
          "issue": 1,
          "review": 2,
          "points": 6
        },
        {
          "pr": 0,
          "issue": 1,
          "review": 1,
          "points": 5
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        }
      ],
      "events": [
        {
          "type": "pr",
          "day": "2026-09-01",
          "title": "feat(dev): add gather-release-notes tool to aggregate PR release notes between tags",
          "url": "https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/12648",
          "repo": "GoogleCloudPlatform/k8s-config-connector",
          "number": 12648
        },
        {
          "type": "review",
          "day": "2026-09-01",
          "title": "Greenfield: Implement direct controller, E2E fixtures, and fuzzer for ApiHubAttribute",
          "url": "https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/12637",
          "repo": "GoogleCloudPlatform/k8s-config-connector",
          "number": 12637
        },
        {
          "type": "review",
          "day": "2026-09-02",
          "title": "Greenfield: Implement direct controller, E2E fixtures, and fuzzer for APIHubExternalAPI",
          "url": "https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/12671",
          "repo": "GoogleCloudPlatform/k8s-config-connector",
          "number": 12671
        },
        {
          "type": "review",
          "day": "2026-09-02",
          "title": "mockgcp: implement MockGCP and Alignment for ApiHubAttribute",
          "url": "https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/12653",
          "repo": "GoogleCloudPlatform/k8s-config-connector",
          "number": 12653
        },
        {
          "type": "issue",
          "day": "2026-09-03",
          "title": "ai:feat: KCC support for APIHubAttribute",
          "url": "https://github.com/GoogleCloudPlatform/k8s-config-connector/issues/11705",
          "repo": "GoogleCloudPlatform/k8s-config-connector",
          "number": 11705
        },
        {
          "type": "review",
          "day": "2026-09-03",
          "title": "Greenfield: Align MockGCP logs with RealGCP for APIHubExternalAPI",
          "url": "https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/12751",
          "repo": "GoogleCloudPlatform/k8s-config-connector",
          "number": 12751
        },
        {
          "type": "review",
          "day": "2026-09-03",
          "title": "Greenfield: Implement MockGCP and Alignment for APIHubExternalAPI",
          "url": "https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/12723",
          "repo": "GoogleCloudPlatform/k8s-config-connector",
          "number": 12723
        },
        {
          "type": "issue",
          "day": "2026-09-04",
          "title": "ai:feat: KCC support for APIHubExternalAPI",
          "url": "https://github.com/GoogleCloudPlatform/k8s-config-connector/issues/12660",
          "repo": "GoogleCloudPlatform/k8s-config-connector",
          "number": 12660
        },
        {
          "type": "review",
          "day": "2026-09-04",
          "title": "Greenfield: Implement direct controller, E2E fixtures, and fuzzer for APIHubDependency",
          "url": "https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/12644",
          "repo": "GoogleCloudPlatform/k8s-config-connector",
          "number": 12644
        }
      ]
    },
    {
      "login": "barney-s",
      "name": "Barni",
      "car": "van",
      "carLabel": "Van",
      "color": "#6bff8f",
      "speed": 1,
      "totals": {
        "pr": 0,
        "issue": 7,
        "review": 32,
        "points": 60,
        "distance": 60
      },
      "daily": [
        {
          "pr": 0,
          "issue": 3,
          "review": 11,
          "points": 23
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 5,
          "points": 5
        },
        {
          "pr": 0,
          "issue": 4,
          "review": 12,
          "points": 28
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 3,
          "points": 3
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 1,
          "points": 1
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        }
      ],
      "events": [
        {
          "type": "issue",
          "day": "2026-09-01",
          "title": "ai:feat: KCC support for APIHubAPI",
          "url": "https://github.com/GoogleCloudPlatform/k8s-config-connector/issues/11132",
          "repo": "GoogleCloudPlatform/k8s-config-connector",
          "number": 11132
        },
        {
          "type": "issue",
          "day": "2026-09-01",
          "title": "ai:feat: KCC support for ConfigDeliveryFleetPackage",
          "url": "https://github.com/GoogleCloudPlatform/k8s-config-connector/issues/11047",
          "repo": "GoogleCloudPlatform/k8s-config-connector",
          "number": 11047
        },
        {
          "type": "issue",
          "day": "2026-09-01",
          "title": "ai:feat: KCC support for CCInsightsPhraseMatcher",
          "url": "https://github.com/GoogleCloudPlatform/k8s-config-connector/issues/11041",
          "repo": "GoogleCloudPlatform/k8s-config-connector",
          "number": 11041
        },
        {
          "type": "review",
          "day": "2026-09-01",
          "title": "Greenfield: Implement MockGCP and Alignment for CCInsightsView",
          "url": "https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/12666",
          "repo": "GoogleCloudPlatform/k8s-config-connector",
          "number": 12666
        },
        {
          "type": "review",
          "day": "2026-09-01",
          "title": "Greenfield: Align MockGCP logs with RealGCP for APIHubAPI",
          "url": "https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/12659",
          "repo": "GoogleCloudPlatform/k8s-config-connector",
          "number": 12659
        },
        {
          "type": "review",
          "day": "2026-09-01",
          "title": "Greenfield: Align MockGCP logs with RealGCP for CCInsightsPhraseMatcher",
          "url": "https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/12656",
          "repo": "GoogleCloudPlatform/k8s-config-connector",
          "number": 12656
        },
        {
          "type": "review",
          "day": "2026-09-01",
          "title": "Greenfield: Implement direct controller, E2E fixtures, and fuzzer for APIHubAPI",
          "url": "https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/12655",
          "repo": "GoogleCloudPlatform/k8s-config-connector",
          "number": 12655
        },
        {
          "type": "review",
          "day": "2026-09-01",
          "title": "Greenfield: Implement direct controller for CCInsightsView",
          "url": "https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/12650",
          "repo": "GoogleCloudPlatform/k8s-config-connector",
          "number": 12650
        },
        {
          "type": "review",
          "day": "2026-09-01",
          "title": "feat(dev): add gather-release-notes tool to aggregate PR release notes between tags",
          "url": "https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/12648",
          "repo": "GoogleCloudPlatform/k8s-config-connector",
          "number": 12648
        },
        {
          "type": "review",
          "day": "2026-09-01",
          "title": "Greenfield: Implement MockGCP and Alignment for CCInsightsPhraseMatcher",
          "url": "https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/12647",
          "repo": "GoogleCloudPlatform/k8s-config-connector",
          "number": 12647
        },
        {
          "type": "review",
          "day": "2026-09-01",
          "title": "Greenfield: Implement direct controller for CCInsightsPhraseMatcher",
          "url": "https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/12645",
          "repo": "GoogleCloudPlatform/k8s-config-connector",
          "number": 12645
        },
        {
          "type": "review",
          "day": "2026-09-01",
          "title": "Greenfield: Implement direct controller, E2E fixtures, and fuzzer for ConfigDeliveryFleetPackage",
          "url": "https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/12543",
          "repo": "GoogleCloudPlatform/k8s-config-connector",
          "number": 12543
        },
        {
          "type": "review",
          "day": "2026-09-01",
          "title": "Greenfield: Verify and journal KRM types and identity for APIHubAPI",
          "url": "https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/12417",
          "repo": "GoogleCloudPlatform/k8s-config-connector",
          "number": 12417
        },
        {
          "type": "review",
          "day": "2026-09-01",
          "title": "Greenfield: Implement direct KRM types, identity, and generate.sh for CCInsightsView",
          "url": "https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/12393",
          "repo": "GoogleCloudPlatform/k8s-config-connector",
          "number": 12393
        },
        {
          "type": "review",
          "day": "2026-09-02",
          "title": "Greenfield: Align MockGCP logs with RealGCP for ApiHubAttribute",
          "url": "https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/12715",
          "repo": "GoogleCloudPlatform/k8s-config-connector",
          "number": 12715
        },
        {
          "type": "review",
          "day": "2026-09-02",
          "title": "Greenfield: Implement MockGCP and Alignment for DialogflowGenerator",
          "url": "https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/12708",
          "repo": "GoogleCloudPlatform/k8s-config-connector",
          "number": 12708
        },
        {
          "type": "review",
          "day": "2026-09-02",
          "title": "saasservicemgmt: implement direct controller for SaasServiceMgmtRelease",
          "url": "https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/12694",
          "repo": "GoogleCloudPlatform/k8s-config-connector",
          "number": 12694
        },
        {
          "type": "review",
          "day": "2026-09-02",
          "title": "Greenfield: Implement direct controller for DialogflowGenerator",
          "url": "https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/12688",
          "repo": "GoogleCloudPlatform/k8s-config-connector",
          "number": 12688
        },
        {
          "type": "review",
          "day": "2026-09-02",
          "title": "Release Notes 1.156.0",
          "url": "https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/12624",
          "repo": "GoogleCloudPlatform/k8s-config-connector",
          "number": 12624
        },
        {
          "type": "issue",
          "day": "2026-09-03",
          "title": "ai:feat: KCC support for APIHubDeployment",
          "url": "https://github.com/GoogleCloudPlatform/k8s-config-connector/issues/11142",
          "repo": "GoogleCloudPlatform/k8s-config-connector",
          "number": 11142
        },
        {
          "type": "issue",
          "day": "2026-09-03",
          "title": "ai:feat: KCC support for SaasServiceMgmtRelease",
          "url": "https://github.com/GoogleCloudPlatform/k8s-config-connector/issues/11139",
          "repo": "GoogleCloudPlatform/k8s-config-connector",
          "number": 11139
        },
        {
          "type": "issue",
          "day": "2026-09-03",
          "title": "ai:feat: KCC support for DialogflowGenerator",
          "url": "https://github.com/GoogleCloudPlatform/k8s-config-connector/issues/11058",
          "repo": "GoogleCloudPlatform/k8s-config-connector",
          "number": 11058
        },
        {
          "type": "issue",
          "day": "2026-09-03",
          "title": "ai:feat: KCC support for CCInsightsView",
          "url": "https://github.com/GoogleCloudPlatform/k8s-config-connector/issues/11042",
          "repo": "GoogleCloudPlatform/k8s-config-connector",
          "number": 11042
        },
        {
          "type": "review",
          "day": "2026-09-03",
          "title": "mockgcp: align APIHubDeployment mock logs with real GCP responses",
          "url": "https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/12744",
          "repo": "GoogleCloudPlatform/k8s-config-connector",
          "number": 12744
        },
        {
          "type": "review",
          "day": "2026-09-03",
          "title": "chore(deps): bump golang from 1.26.5 to 1.27.1 in /operator",
          "url": "https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/12736",
          "repo": "GoogleCloudPlatform/k8s-config-connector",
          "number": 12736
        },
        {
          "type": "review",
          "day": "2026-09-03",
          "title": "mockgcp: align SaasServiceMgmtRelease mock with real GCP responses",
          "url": "https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/12734",
          "repo": "GoogleCloudPlatform/k8s-config-connector",
          "number": 12734
        },
        {
          "type": "review",
          "day": "2026-09-03",
          "title": "Greenfield: Implement MockGCP and Alignment for APIHubDeployment",
          "url": "https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/12732",
          "repo": "GoogleCloudPlatform/k8s-config-connector",
          "number": 12732
        },
        {
          "type": "review",
          "day": "2026-09-03",
          "title": "mockgcp: align MockGCP logs with RealGCP for DialogflowGenerator",
          "url": "https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/12728",
          "repo": "GoogleCloudPlatform/k8s-config-connector",
          "number": 12728
        },
        {
          "type": "review",
          "day": "2026-09-03",
          "title": "chore: Update cp_resources_list with parent and references details",
          "url": "https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/12727",
          "repo": "GoogleCloudPlatform/k8s-config-connector",
          "number": 12727
        },
        {
          "type": "review",
          "day": "2026-09-03",
          "title": "Greenfield: Implement direct controller, E2E fixtures, and fuzzer for APIHubDeployment",
          "url": "https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/12721",
          "repo": "GoogleCloudPlatform/k8s-config-connector",
          "number": 12721
        },
        {
          "type": "review",
          "day": "2026-09-03",
          "title": "mockgcp: implement MockGCP and Alignment for SaasServiceMgmtRelease",
          "url": "https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/12718",
          "repo": "GoogleCloudPlatform/k8s-config-connector",
          "number": 12718
        },
        {
          "type": "review",
          "day": "2026-09-03",
          "title": "skills(reviewgen): avoid switching default controller when legacy exists",
          "url": "https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/12706",
          "repo": "GoogleCloudPlatform/k8s-config-connector",
          "number": 12706
        },
        {
          "type": "review",
          "day": "2026-09-03",
          "title": "Greenfield: Fix CCInsightsAnalysisRule Identity format and add E2E presubmit",
          "url": "https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/12689",
          "repo": "GoogleCloudPlatform/k8s-config-connector",
          "number": 12689
        },
        {
          "type": "review",
          "day": "2026-09-03",
          "title": "Greenfield: Align MockGCP logs with RealGCP for CCInsightsView",
          "url": "https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/12684",
          "repo": "GoogleCloudPlatform/k8s-config-connector",
          "number": 12684
        },
        {
          "type": "review",
          "day": "2026-09-03",
          "title": "Greenfield: Implement MockGCP and Alignment for StorageInsightsDatasetConfig",
          "url": "https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/12421",
          "repo": "GoogleCloudPlatform/k8s-config-connector",
          "number": 12421
        },
        {
          "type": "review",
          "day": "2026-09-04",
          "title": "Revert \"fix(container): default cpu_cfs_quota to true in ContainerNodePool kubeletConfig\"",
          "url": "https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/12778",
          "repo": "GoogleCloudPlatform/k8s-config-connector",
          "number": 12778
        },
        {
          "type": "review",
          "day": "2026-09-04",
          "title": "Greenfield: Implement direct controller, E2E fixtures, and fuzzer for AIPlatformModel",
          "url": "https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/12702",
          "repo": "GoogleCloudPlatform/k8s-config-connector",
          "number": 12702
        },
        {
          "type": "review",
          "day": "2026-09-04",
          "title": "Greenfield: Implement MockGCP and Alignment for DeviceStreamingSession",
          "url": "https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/12253",
          "repo": "GoogleCloudPlatform/k8s-config-connector",
          "number": 12253
        },
        {
          "type": "review",
          "day": "2026-09-05",
          "title": "Support Pause at resource-level",
          "url": "https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/12731",
          "repo": "GoogleCloudPlatform/k8s-config-connector",
          "number": 12731
        }
      ]
    },
    {
      "login": "gemmahou",
      "name": "Gemma",
      "car": "van",
      "carLabel": "Van",
      "color": "#b06bff",
      "speed": 1,
      "totals": {
        "pr": 3,
        "issue": 4,
        "review": 11,
        "points": 33,
        "distance": 33
      },
      "daily": [
        {
          "pr": 0,
          "issue": 0,
          "review": 3,
          "points": 3
        },
        {
          "pr": 1,
          "issue": 3,
          "review": 6,
          "points": 20
        },
        {
          "pr": 2,
          "issue": 1,
          "review": 0,
          "points": 8
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 2,
          "points": 2
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        }
      ],
      "events": [
        {
          "type": "review",
          "day": "2026-09-01",
          "title": "Revert PR#8686: ai:chore: Implement direct types for ContentWarehouseSchema",
          "url": "https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/12549",
          "repo": "GoogleCloudPlatform/k8s-config-connector",
          "number": 12549
        },
        {
          "type": "review",
          "day": "2026-09-01",
          "title": "Revert Greenfield: Implement direct KRM types, identity, and generate.sh for CloudSecurityFramework",
          "url": "https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/12547",
          "repo": "GoogleCloudPlatform/k8s-config-connector",
          "number": 12547
        },
        {
          "type": "review",
          "day": "2026-09-01",
          "title": "Greenfield: Implement direct controller, E2E fixtures, and fuzzer for VertexAIExtension",
          "url": "https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/12411",
          "repo": "GoogleCloudPlatform/k8s-config-connector",
          "number": 12411
        },
        {
          "type": "pr",
          "day": "2026-09-02",
          "title": "feat: Add direct controller for RedisClusterEndpoint",
          "url": "https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/11639",
          "repo": "GoogleCloudPlatform/k8s-config-connector",
          "number": 11639
        },
        {
          "type": "issue",
          "day": "2026-09-02",
          "title": "ai:feat: KCC support for AIPlatformModel",
          "url": "https://github.com/GoogleCloudPlatform/k8s-config-connector/issues/12007",
          "repo": "GoogleCloudPlatform/k8s-config-connector",
          "number": 12007
        },
        {
          "type": "issue",
          "day": "2026-09-02",
          "title": "Add direct controller for RedisClusterEndpoint",
          "url": "https://github.com/GoogleCloudPlatform/k8s-config-connector/issues/11614",
          "repo": "GoogleCloudPlatform/k8s-config-connector",
          "number": 11614
        },
        {
          "type": "issue",
          "day": "2026-09-02",
          "title": "ai:feat: KCC support for AIPlatformCachedContent",
          "url": "https://github.com/GoogleCloudPlatform/k8s-config-connector/issues/11377",
          "repo": "GoogleCloudPlatform/k8s-config-connector",
          "number": 11377
        },
        {
          "type": "review",
          "day": "2026-09-02",
          "title": "Revert PR#8419 and #11381 for BeyondCorpClientGateway",
          "url": "https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/12695",
          "repo": "GoogleCloudPlatform/k8s-config-connector",
          "number": 12695
        },
        {
          "type": "review",
          "day": "2026-09-02",
          "title": "Revert PR#9017 ai:chore: Implement direct types for: BlockchainNodeEngineBlockchainNode",
          "url": "https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/12675",
          "repo": "GoogleCloudPlatform/k8s-config-connector",
          "number": 12675
        },
        {
          "type": "review",
          "day": "2026-09-02",
          "title": "revert DataLabelingDataset implementation due to deprecation",
          "url": "https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/12673",
          "repo": "GoogleCloudPlatform/k8s-config-connector",
          "number": 12673
        },
        {
          "type": "review",
          "day": "2026-09-02",
          "title": "Revert PR#9269 ai:chore: Implement direct types for: DataLabelingEvaluationJob",
          "url": "https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/12672",
          "repo": "GoogleCloudPlatform/k8s-config-connector",
          "number": 12672
        },
        {
          "type": "review",
          "day": "2026-09-02",
          "title": "Greenfield: Implement direct KRM types, identity, and generate.sh for DialogflowTool",
          "url": "https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/12643",
          "repo": "GoogleCloudPlatform/k8s-config-connector",
          "number": 12643
        },
        {
          "type": "review",
          "day": "2026-09-02",
          "title": "ai:chore: Implement direct types for: VertexAIRagCorpus",
          "url": "https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/11389",
          "repo": "GoogleCloudPlatform/k8s-config-connector",
          "number": 11389
        },
        {
          "type": "pr",
          "day": "2026-09-03",
          "title": "chore: Update cp_resources_list with parent and references details",
          "url": "https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/12727",
          "repo": "GoogleCloudPlatform/k8s-config-connector",
          "number": 12727
        },
        {
          "type": "pr",
          "day": "2026-09-03",
          "title": "chore: Document known deprecated services and update gap analysis",
          "url": "https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/12676",
          "repo": "GoogleCloudPlatform/k8s-config-connector",
          "number": 12676
        },
        {
          "type": "issue",
          "day": "2026-09-03",
          "title": "Confirm the resource is not deprecated before generating the types",
          "url": "https://github.com/GoogleCloudPlatform/k8s-config-connector/issues/12649",
          "repo": "GoogleCloudPlatform/k8s-config-connector",
          "number": 12649
        },
        {
          "type": "review",
          "day": "2026-09-04",
          "title": "Greenfield: Implement direct controller, E2E fixtures, and fuzzer for VertexAISchedule",
          "url": "https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/12430",
          "repo": "GoogleCloudPlatform/k8s-config-connector",
          "number": 12430
        },
        {
          "type": "review",
          "day": "2026-09-04",
          "title": "Fix NotebookInstanceV2 and verify against realGCP",
          "url": "https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/12314",
          "repo": "GoogleCloudPlatform/k8s-config-connector",
          "number": 12314
        }
      ]
    },
    {
      "login": "maqiuyujoyce",
      "name": "Joyce",
      "car": "van",
      "carLabel": "Van",
      "color": "#ff9f1c",
      "speed": 1,
      "totals": {
        "pr": 1,
        "issue": 5,
        "review": 13,
        "points": 35,
        "distance": 35
      },
      "daily": [
        {
          "pr": 0,
          "issue": 0,
          "review": 2,
          "points": 2
        },
        {
          "pr": 0,
          "issue": 2,
          "review": 3,
          "points": 11
        },
        {
          "pr": 0,
          "issue": 3,
          "review": 4,
          "points": 16
        },
        {
          "pr": 1,
          "issue": 0,
          "review": 3,
          "points": 5
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 1,
          "points": 1
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        }
      ],
      "events": [
        {
          "type": "review",
          "day": "2026-09-01",
          "title": "Pause re-reconciliation on non-retryable errors until user update",
          "url": "https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/12519",
          "repo": "GoogleCloudPlatform/k8s-config-connector",
          "number": 12519
        },
        {
          "type": "review",
          "day": "2026-09-01",
          "title": "Greenfield: Implement direct controller, E2E fixtures, and fuzzer for VertexAIExtension",
          "url": "https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/12411",
          "repo": "GoogleCloudPlatform/k8s-config-connector",
          "number": 12411
        },
        {
          "type": "issue",
          "day": "2026-09-02",
          "title": "directbase: unhandled Find() errors fall through, causing silent orphaning on delete and invalid creates",
          "url": "https://github.com/GoogleCloudPlatform/k8s-config-connector/issues/12685",
          "repo": "GoogleCloudPlatform/k8s-config-connector",
          "number": 12685
        },
        {
          "type": "issue",
          "day": "2026-09-02",
          "title": "Revert the changes related to VertexAIExtension",
          "url": "https://github.com/GoogleCloudPlatform/k8s-config-connector/issues/12677",
          "repo": "GoogleCloudPlatform/k8s-config-connector",
          "number": 12677
        },
        {
          "type": "review",
          "day": "2026-09-02",
          "title": "directbase: handle Find() errors instead of falling through",
          "url": "https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/12686",
          "repo": "GoogleCloudPlatform/k8s-config-connector",
          "number": 12686
        },
        {
          "type": "review",
          "day": "2026-09-02",
          "title": "Revert support for deprecated VertexAIExtension resource",
          "url": "https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/12680",
          "repo": "GoogleCloudPlatform/k8s-config-connector",
          "number": 12680
        },
        {
          "type": "review",
          "day": "2026-09-02",
          "title": "Release Notes 1.156.0",
          "url": "https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/12624",
          "repo": "GoogleCloudPlatform/k8s-config-connector",
          "number": 12624
        },
        {
          "type": "issue",
          "day": "2026-09-03",
          "title": "ComputeRouterNATRef.Normalize should verify resource readiness before falling back to spec identity",
          "url": "https://github.com/GoogleCloudPlatform/k8s-config-connector/issues/12713",
          "repo": "GoogleCloudPlatform/k8s-config-connector",
          "number": 12713
        },
        {
          "type": "issue",
          "day": "2026-09-03",
          "title": "Clarify nochange test requirements in brownfield migration",
          "url": "https://github.com/GoogleCloudPlatform/k8s-config-connector/issues/12712",
          "repo": "GoogleCloudPlatform/k8s-config-connector",
          "number": 12712
        },
        {
          "type": "issue",
          "day": "2026-09-03",
          "title": "Enable the skill to support service-generated ID for brownfield resources",
          "url": "https://github.com/GoogleCloudPlatform/k8s-config-connector/issues/12704",
          "repo": "GoogleCloudPlatform/k8s-config-connector",
          "number": 12704
        },
        {
          "type": "review",
          "day": "2026-09-03",
          "title": "ComputeRouterNATRef.Normalize: verify resource readiness before spec fallback",
          "url": "https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/12716",
          "repo": "GoogleCloudPlatform/k8s-config-connector",
          "number": 12716
        },
        {
          "type": "review",
          "day": "2026-09-03",
          "title": "Clarify nochange test requirements in brownfield migration",
          "url": "https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/12714",
          "repo": "GoogleCloudPlatform/k8s-config-connector",
          "number": 12714
        },
        {
          "type": "review",
          "day": "2026-09-03",
          "title": "Enable the skill to support service-generated ID for brownfield resources",
          "url": "https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/12705",
          "repo": "GoogleCloudPlatform/k8s-config-connector",
          "number": 12705
        },
        {
          "type": "review",
          "day": "2026-09-03",
          "title": "chore: Document known deprecated services and update gap analysis",
          "url": "https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/12676",
          "repo": "GoogleCloudPlatform/k8s-config-connector",
          "number": 12676
        },
        {
          "type": "pr",
          "day": "2026-09-04",
          "title": "Revert \"fix(container): default cpu_cfs_quota to true in ContainerNodePool kubeletConfig\"",
          "url": "https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/12778",
          "repo": "GoogleCloudPlatform/k8s-config-connector",
          "number": 12778
        },
        {
          "type": "review",
          "day": "2026-09-04",
          "title": "directbase: support unreadable-but-deletable resources",
          "url": "https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/12750",
          "repo": "GoogleCloudPlatform/k8s-config-connector",
          "number": 12750
        },
        {
          "type": "review",
          "day": "2026-09-04",
          "title": "Pause re-reconciliation on terminal client errors purely within status",
          "url": "https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/12730",
          "repo": "GoogleCloudPlatform/k8s-config-connector",
          "number": 12730
        },
        {
          "type": "review",
          "day": "2026-09-04",
          "title": "Fix NotebookInstanceV2 and verify against realGCP",
          "url": "https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/12314",
          "repo": "GoogleCloudPlatform/k8s-config-connector",
          "number": 12314
        },
        {
          "type": "review",
          "day": "2026-09-05",
          "title": "Support Pause at resource-level",
          "url": "https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/12731",
          "repo": "GoogleCloudPlatform/k8s-config-connector",
          "number": 12731
        }
      ]
    },
    {
      "login": "sdowell",
      "name": "Sam",
      "car": "pickup",
      "carLabel": "Pickup",
      "color": "#35d0a0",
      "speed": 1,
      "totals": {
        "pr": 0,
        "issue": 1,
        "review": 3,
        "points": 7,
        "distance": 7
      },
      "daily": [
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 1,
          "points": 1
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 2,
          "points": 2
        },
        {
          "pr": 0,
          "issue": 1,
          "review": 0,
          "points": 4
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        }
      ],
      "events": [
        {
          "type": "review",
          "day": "2026-09-02",
          "title": "docs: Design doc for Resource-Level Actuation Pause and Lifecycle Controls",
          "url": "https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/12657",
          "repo": "GoogleCloudPlatform/k8s-config-connector",
          "number": 12657
        },
        {
          "type": "review",
          "day": "2026-09-03",
          "title": "chore: Update cp_resources_list with parent and references details",
          "url": "https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/12727",
          "repo": "GoogleCloudPlatform/k8s-config-connector",
          "number": 12727
        },
        {
          "type": "review",
          "day": "2026-09-03",
          "title": "Greenfield: Implement direct controller, E2E fixtures, and fuzzer for AssuredWorkloadsWorkload",
          "url": "https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/12440",
          "repo": "GoogleCloudPlatform/k8s-config-connector",
          "number": 12440
        },
        {
          "type": "issue",
          "day": "2026-09-04",
          "title": "ai:feat: KCC support for DataMigrationConversionWorkspace",
          "url": "https://github.com/GoogleCloudPlatform/k8s-config-connector/issues/11049",
          "repo": "GoogleCloudPlatform/k8s-config-connector",
          "number": 11049
        }
      ]
    },
    {
      "login": "ldanielmadariaga",
      "name": "Lucas",
      "car": "pickup",
      "carLabel": "Pickup",
      "color": "#ff77c8",
      "speed": 1,
      "totals": {
        "pr": 0,
        "issue": 0,
        "review": 4,
        "points": 4,
        "distance": 4
      },
      "daily": [
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 2,
          "points": 2
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 1,
          "points": 1
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 1,
          "points": 1
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        }
      ],
      "events": [
        {
          "type": "review",
          "day": "2026-09-02",
          "title": "ComputeNetworkFirewallPolicyRule: add support for srcNetworkContext and destNetworkContext fields",
          "url": "https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/11784",
          "repo": "GoogleCloudPlatform/k8s-config-connector",
          "number": 11784
        },
        {
          "type": "review",
          "day": "2026-09-02",
          "title": "feat: Add direct controller for RedisClusterEndpoint",
          "url": "https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/11639",
          "repo": "GoogleCloudPlatform/k8s-config-connector",
          "number": 11639
        },
        {
          "type": "review",
          "day": "2026-09-03",
          "title": "chore: Document known deprecated services and update gap analysis",
          "url": "https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/12676",
          "repo": "GoogleCloudPlatform/k8s-config-connector",
          "number": 12676
        },
        {
          "type": "review",
          "day": "2026-09-04",
          "title": "Improve the CRD equivalence check",
          "url": "https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/9611",
          "repo": "GoogleCloudPlatform/k8s-config-connector",
          "number": 9611
        }
      ]
    },
    {
      "login": "justinsb",
      "name": "Justin",
      "car": "sports",
      "carLabel": "Sports",
      "color": "#5b8cff",
      "speed": 2,
      "totals": {
        "pr": 0,
        "issue": 0,
        "review": 0,
        "points": 0,
        "distance": 0
      },
      "daily": [
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        }
      ],
      "events": []
    },
    {
      "login": "cheftako",
      "name": "Walter",
      "car": "supercar",
      "carLabel": "Supercar",
      "color": "#d4ff4d",
      "speed": 2,
      "totals": {
        "pr": 0,
        "issue": 0,
        "review": 1,
        "points": 1,
        "distance": 2
      },
      "daily": [
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 1,
          "points": 1
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        }
      ],
      "events": [
        {
          "type": "review",
          "day": "2026-09-04",
          "title": "Greenfield: Implement direct KRM types, identity, and generate.sh for APIHubCuration",
          "url": "https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/11729",
          "repo": "GoogleCloudPlatform/k8s-config-connector",
          "number": 11729
        }
      ]
    },
    {
      "login": "seans3",
      "name": "Sean",
      "car": "f1",
      "carLabel": "Formula",
      "color": "#ff6b4a",
      "speed": 2,
      "totals": {
        "pr": 0,
        "issue": 0,
        "review": 0,
        "points": 0,
        "distance": 0
      },
      "daily": [
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        }
      ],
      "events": []
    },
    {
      "login": "yliaog",
      "name": "Yu",
      "car": "supercar",
      "carLabel": "Supercar",
      "color": "#4ee1ff",
      "speed": 2,
      "totals": {
        "pr": 0,
        "issue": 0,
        "review": 0,
        "points": 0,
        "distance": 0
      },
      "daily": [
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        }
      ],
      "events": []
    },
    {
      "login": "ziyue-101",
      "name": "Ziyue",
      "car": "supercar",
      "carLabel": "Supercar",
      "color": "#c084fc",
      "speed": 2,
      "totals": {
        "pr": 0,
        "issue": 0,
        "review": 1,
        "points": 1,
        "distance": 2
      },
      "daily": [
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 1,
          "points": 1
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        }
      ],
      "events": [
        {
          "type": "review",
          "day": "2026-09-04",
          "title": "Greenfield: Implement direct controller, E2E fixtures, and fuzzer for AIPlatformModel",
          "url": "https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/12702",
          "repo": "GoogleCloudPlatform/k8s-config-connector",
          "number": 12702
        }
      ]
    },
    {
      "login": "GinnyJI",
      "name": "Ginny",
      "car": "f1",
      "carLabel": "Formula",
      "color": "#ffbf69",
      "speed": 2,
      "totals": {
        "pr": 0,
        "issue": 0,
        "review": 1,
        "points": 1,
        "distance": 2
      },
      "daily": [
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 1,
          "points": 1
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        }
      ],
      "events": [
        {
          "type": "review",
          "day": "2026-09-04",
          "title": "Greenfield: Implement direct controller, E2E fixtures, and fuzzer for ContactCenterInsightsConversation",
          "url": "https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/12432",
          "repo": "GoogleCloudPlatform/k8s-config-connector",
          "number": 12432
        }
      ]
    },
    {
      "login": "himanigulati01",
      "name": "Himani",
      "car": "f1",
      "carLabel": "Formula",
      "color": "#22d3a5",
      "speed": 2,
      "totals": {
        "pr": 0,
        "issue": 0,
        "review": 1,
        "points": 1,
        "distance": 2
      },
      "daily": [
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 1,
          "points": 1
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        }
      ],
      "events": [
        {
          "type": "review",
          "day": "2026-09-04",
          "title": "Greenfield: Implement direct controller, E2E fixtures, and fuzzer for NetworkSecurityInterceptDeployment",
          "url": "https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/12711",
          "repo": "GoogleCloudPlatform/k8s-config-connector",
          "number": 12711
        }
      ]
    }
  ]
};
