// Generated by scripts/fetch.js — do not edit by hand.
window.RACE_DATA = {
  "generatedAt": "2026-09-01T23:00:58.886Z",
  "demo": false,
  "title": "KCC Grand Prix",
  "subtitle": "Merged PRs, closed issues and reviews — as a race",
  "period": {
    "since": "2026-09-01",
    "until": "2026-09-30"
  },
  "scope": {
    "orgs": [
      "GoogleCloudPlatform"
    ],
    "repos": [
      "k8s-config-connector"
    ]
  },
  "scoring": {
    "mergedPR": 2,
    "issueClosed": 4,
    "reviewSubmitted": 1
  },
  "cars": {
    "f1": {
      "label": "Formula",
      "speed": 2
    },
    "supercar": {
      "label": "Supercar",
      "speed": 2
    },
    "sports": {
      "label": "Sports",
      "speed": 2
    },
    "muscle": {
      "label": "Muscle",
      "speed": 1
    },
    "hatchback": {
      "label": "Hot hatch",
      "speed": 1
    },
    "pickup": {
      "label": "Pickup",
      "speed": 1
    },
    "van": {
      "label": "Van",
      "speed": 1
    },
    "tractor": {
      "label": "Tractor",
      "speed": 1
    }
  },
  "days": [
    "2026-09-01",
    "2026-09-02",
    "2026-09-03",
    "2026-09-04",
    "2026-09-05",
    "2026-09-06",
    "2026-09-07",
    "2026-09-08",
    "2026-09-09",
    "2026-09-10",
    "2026-09-11",
    "2026-09-12",
    "2026-09-13",
    "2026-09-14",
    "2026-09-15",
    "2026-09-16",
    "2026-09-17",
    "2026-09-18",
    "2026-09-19",
    "2026-09-20",
    "2026-09-21",
    "2026-09-22",
    "2026-09-23",
    "2026-09-24",
    "2026-09-25",
    "2026-09-26",
    "2026-09-27",
    "2026-09-28",
    "2026-09-29",
    "2026-09-30"
  ],
  "racers": [
    {
      "login": "anfernee",
      "name": "Yongkun",
      "car": "tractor",
      "carLabel": "Tractor",
      "color": "#ff3b6b",
      "speed": 1,
      "totals": {
        "pr": 0,
        "issue": 0,
        "review": 0,
        "points": 0,
        "distance": 0
      },
      "daily": [
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        }
      ],
      "events": []
    },
    {
      "login": "acpana",
      "name": "Alex",
      "car": "tractor",
      "carLabel": "Tractor",
      "color": "#00e0ff",
      "speed": 1,
      "totals": {
        "pr": 0,
        "issue": 0,
        "review": 2,
        "points": 2,
        "distance": 2
      },
      "daily": [
        {
          "pr": 0,
          "issue": 0,
          "review": 2,
          "points": 2
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        }
      ],
      "events": [
        {
          "type": "review",
          "day": "2026-09-01",
          "title": "Greenfield: Implement direct KRM types, identity, and generate.sh for APIHubCuration",
          "url": "https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/11729",
          "repo": "GoogleCloudPlatform/k8s-config-connector",
          "number": 11729
        },
        {
          "type": "review",
          "day": "2026-09-01",
          "title": "Implement direct KRM types and IdentityV2 for CCInsightsAnalysisRule",
          "url": "https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/11169",
          "repo": "GoogleCloudPlatform/k8s-config-connector",
          "number": 11169
        }
      ]
    },
    {
      "login": "anhdle-sso",
      "name": "Anh",
      "car": "tractor",
      "carLabel": "Tractor",
      "color": "#ffd23f",
      "speed": 1,
      "totals": {
        "pr": 1,
        "issue": 0,
        "review": 1,
        "points": 3,
        "distance": 3
      },
      "daily": [
        {
          "pr": 1,
          "issue": 0,
          "review": 1,
          "points": 3
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        }
      ],
      "events": [
        {
          "type": "pr",
          "day": "2026-09-01",
          "title": "feat(dev): add gather-release-notes tool to aggregate PR release notes between tags",
          "url": "https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/12648",
          "repo": "GoogleCloudPlatform/k8s-config-connector",
          "number": 12648
        },
        {
          "type": "review",
          "day": "2026-09-01",
          "title": "Greenfield: Implement direct controller, E2E fixtures, and fuzzer for ApiHubAttribute",
          "url": "https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/12637",
          "repo": "GoogleCloudPlatform/k8s-config-connector",
          "number": 12637
        }
      ]
    },
    {
      "login": "barney-s",
      "name": "Barni",
      "car": "van",
      "carLabel": "Van",
      "color": "#6bff8f",
      "speed": 1,
      "totals": {
        "pr": 0,
        "issue": 3,
        "review": 11,
        "points": 23,
        "distance": 23
      },
      "daily": [
        {
          "pr": 0,
          "issue": 3,
          "review": 11,
          "points": 23
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        }
      ],
      "events": [
        {
          "type": "issue",
          "day": "2026-09-01",
          "title": "ai:feat: KCC support for APIHubAPI",
          "url": "https://github.com/GoogleCloudPlatform/k8s-config-connector/issues/11132",
          "repo": "GoogleCloudPlatform/k8s-config-connector",
          "number": 11132
        },
        {
          "type": "issue",
          "day": "2026-09-01",
          "title": "ai:feat: KCC support for ConfigDeliveryFleetPackage",
          "url": "https://github.com/GoogleCloudPlatform/k8s-config-connector/issues/11047",
          "repo": "GoogleCloudPlatform/k8s-config-connector",
          "number": 11047
        },
        {
          "type": "issue",
          "day": "2026-09-01",
          "title": "ai:feat: KCC support for CCInsightsPhraseMatcher",
          "url": "https://github.com/GoogleCloudPlatform/k8s-config-connector/issues/11041",
          "repo": "GoogleCloudPlatform/k8s-config-connector",
          "number": 11041
        },
        {
          "type": "review",
          "day": "2026-09-01",
          "title": "Greenfield: Implement MockGCP and Alignment for CCInsightsView",
          "url": "https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/12666",
          "repo": "GoogleCloudPlatform/k8s-config-connector",
          "number": 12666
        },
        {
          "type": "review",
          "day": "2026-09-01",
          "title": "Greenfield: Align MockGCP logs with RealGCP for APIHubAPI",
          "url": "https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/12659",
          "repo": "GoogleCloudPlatform/k8s-config-connector",
          "number": 12659
        },
        {
          "type": "review",
          "day": "2026-09-01",
          "title": "Greenfield: Align MockGCP logs with RealGCP for CCInsightsPhraseMatcher",
          "url": "https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/12656",
          "repo": "GoogleCloudPlatform/k8s-config-connector",
          "number": 12656
        },
        {
          "type": "review",
          "day": "2026-09-01",
          "title": "Greenfield: Implement direct controller, E2E fixtures, and fuzzer for APIHubAPI",
          "url": "https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/12655",
          "repo": "GoogleCloudPlatform/k8s-config-connector",
          "number": 12655
        },
        {
          "type": "review",
          "day": "2026-09-01",
          "title": "Greenfield: Implement direct controller for CCInsightsView",
          "url": "https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/12650",
          "repo": "GoogleCloudPlatform/k8s-config-connector",
          "number": 12650
        },
        {
          "type": "review",
          "day": "2026-09-01",
          "title": "feat(dev): add gather-release-notes tool to aggregate PR release notes between tags",
          "url": "https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/12648",
          "repo": "GoogleCloudPlatform/k8s-config-connector",
          "number": 12648
        },
        {
          "type": "review",
          "day": "2026-09-01",
          "title": "Greenfield: Implement MockGCP and Alignment for CCInsightsPhraseMatcher",
          "url": "https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/12647",
          "repo": "GoogleCloudPlatform/k8s-config-connector",
          "number": 12647
        },
        {
          "type": "review",
          "day": "2026-09-01",
          "title": "Greenfield: Implement direct controller for CCInsightsPhraseMatcher",
          "url": "https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/12645",
          "repo": "GoogleCloudPlatform/k8s-config-connector",
          "number": 12645
        },
        {
          "type": "review",
          "day": "2026-09-01",
          "title": "Greenfield: Implement direct controller, E2E fixtures, and fuzzer for ConfigDeliveryFleetPackage",
          "url": "https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/12543",
          "repo": "GoogleCloudPlatform/k8s-config-connector",
          "number": 12543
        },
        {
          "type": "review",
          "day": "2026-09-01",
          "title": "Greenfield: Verify and journal KRM types and identity for APIHubAPI",
          "url": "https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/12417",
          "repo": "GoogleCloudPlatform/k8s-config-connector",
          "number": 12417
        },
        {
          "type": "review",
          "day": "2026-09-01",
          "title": "Greenfield: Implement direct KRM types, identity, and generate.sh for CCInsightsView",
          "url": "https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/12393",
          "repo": "GoogleCloudPlatform/k8s-config-connector",
          "number": 12393
        }
      ]
    },
    {
      "login": "gemmahou",
      "name": "Gemma",
      "car": "van",
      "carLabel": "Van",
      "color": "#b06bff",
      "speed": 1,
      "totals": {
        "pr": 0,
        "issue": 0,
        "review": 4,
        "points": 4,
        "distance": 4
      },
      "daily": [
        {
          "pr": 0,
          "issue": 0,
          "review": 4,
          "points": 4
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        }
      ],
      "events": [
        {
          "type": "review",
          "day": "2026-09-01",
          "title": "Greenfield: Implement direct KRM types, identity, and generate.sh for DialogflowTool",
          "url": "https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/12643",
          "repo": "GoogleCloudPlatform/k8s-config-connector",
          "number": 12643
        },
        {
          "type": "review",
          "day": "2026-09-01",
          "title": "Revert PR#8686: ai:chore: Implement direct types for ContentWarehouseSchema",
          "url": "https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/12549",
          "repo": "GoogleCloudPlatform/k8s-config-connector",
          "number": 12549
        },
        {
          "type": "review",
          "day": "2026-09-01",
          "title": "Revert Greenfield: Implement direct KRM types, identity, and generate.sh for CloudSecurityFramework",
          "url": "https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/12547",
          "repo": "GoogleCloudPlatform/k8s-config-connector",
          "number": 12547
        },
        {
          "type": "review",
          "day": "2026-09-01",
          "title": "Greenfield: Implement direct controller, E2E fixtures, and fuzzer for VertexAIExtension",
          "url": "https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/12411",
          "repo": "GoogleCloudPlatform/k8s-config-connector",
          "number": 12411
        }
      ]
    },
    {
      "login": "maqiuyujoyce",
      "name": "Joyce",
      "car": "van",
      "carLabel": "Van",
      "color": "#ff9f1c",
      "speed": 1,
      "totals": {
        "pr": 0,
        "issue": 0,
        "review": 3,
        "points": 3,
        "distance": 3
      },
      "daily": [
        {
          "pr": 0,
          "issue": 0,
          "review": 3,
          "points": 3
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        }
      ],
      "events": [
        {
          "type": "review",
          "day": "2026-09-01",
          "title": "Release Notes 1.156.0",
          "url": "https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/12624",
          "repo": "GoogleCloudPlatform/k8s-config-connector",
          "number": 12624
        },
        {
          "type": "review",
          "day": "2026-09-01",
          "title": "Pause re-reconciliation on non-retryable errors until user update",
          "url": "https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/12519",
          "repo": "GoogleCloudPlatform/k8s-config-connector",
          "number": 12519
        },
        {
          "type": "review",
          "day": "2026-09-01",
          "title": "Greenfield: Implement direct controller, E2E fixtures, and fuzzer for VertexAIExtension",
          "url": "https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/12411",
          "repo": "GoogleCloudPlatform/k8s-config-connector",
          "number": 12411
        }
      ]
    },
    {
      "login": "sdowell",
      "name": "Sam",
      "car": "pickup",
      "carLabel": "Pickup",
      "color": "#35d0a0",
      "speed": 1,
      "totals": {
        "pr": 0,
        "issue": 0,
        "review": 1,
        "points": 1,
        "distance": 1
      },
      "daily": [
        {
          "pr": 0,
          "issue": 0,
          "review": 1,
          "points": 1
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        }
      ],
      "events": [
        {
          "type": "review",
          "day": "2026-09-01",
          "title": "docs: Design doc for Resource-Level Actuation Pause and Lifecycle Controls",
          "url": "https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/12657",
          "repo": "GoogleCloudPlatform/k8s-config-connector",
          "number": 12657
        }
      ]
    },
    {
      "login": "ldanielmadariaga",
      "name": "Lucas",
      "car": "pickup",
      "carLabel": "Pickup",
      "color": "#ff77c8",
      "speed": 1,
      "totals": {
        "pr": 0,
        "issue": 0,
        "review": 2,
        "points": 2,
        "distance": 2
      },
      "daily": [
        {
          "pr": 0,
          "issue": 0,
          "review": 2,
          "points": 2
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        }
      ],
      "events": [
        {
          "type": "review",
          "day": "2026-09-01",
          "title": "ComputeNetworkFirewallPolicyRule: add support for srcNetworkContext and destNetworkContext fields",
          "url": "https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/11784",
          "repo": "GoogleCloudPlatform/k8s-config-connector",
          "number": 11784
        },
        {
          "type": "review",
          "day": "2026-09-01",
          "title": "feat: Add direct controller for RedisClusterEndpoint",
          "url": "https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/11639",
          "repo": "GoogleCloudPlatform/k8s-config-connector",
          "number": 11639
        }
      ]
    },
    {
      "login": "justinsb",
      "name": "Justin",
      "car": "sports",
      "carLabel": "Sports",
      "color": "#5b8cff",
      "speed": 2,
      "totals": {
        "pr": 0,
        "issue": 0,
        "review": 0,
        "points": 0,
        "distance": 0
      },
      "daily": [
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        }
      ],
      "events": []
    },
    {
      "login": "cheftako",
      "name": "Walter",
      "car": "supercar",
      "carLabel": "Supercar",
      "color": "#d4ff4d",
      "speed": 2,
      "totals": {
        "pr": 0,
        "issue": 0,
        "review": 1,
        "points": 1,
        "distance": 2
      },
      "daily": [
        {
          "pr": 0,
          "issue": 0,
          "review": 1,
          "points": 1
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        }
      ],
      "events": [
        {
          "type": "review",
          "day": "2026-09-01",
          "title": "Greenfield: Implement direct KRM types, identity, and generate.sh for APIHubCuration",
          "url": "https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/11729",
          "repo": "GoogleCloudPlatform/k8s-config-connector",
          "number": 11729
        }
      ]
    },
    {
      "login": "seans3",
      "name": "Sean",
      "car": "f1",
      "carLabel": "Formula",
      "color": "#ff6b4a",
      "speed": 2,
      "totals": {
        "pr": 0,
        "issue": 0,
        "review": 0,
        "points": 0,
        "distance": 0
      },
      "daily": [
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        }
      ],
      "events": []
    },
    {
      "login": "yliaog",
      "name": "Yu",
      "car": "supercar",
      "carLabel": "Supercar",
      "color": "#4ee1ff",
      "speed": 2,
      "totals": {
        "pr": 0,
        "issue": 0,
        "review": 0,
        "points": 0,
        "distance": 0
      },
      "daily": [
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        }
      ],
      "events": []
    },
    {
      "login": "ziyue-101",
      "name": "Ziyue",
      "car": "supercar",
      "carLabel": "Supercar",
      "color": "#c084fc",
      "speed": 2,
      "totals": {
        "pr": 0,
        "issue": 0,
        "review": 0,
        "points": 0,
        "distance": 0
      },
      "daily": [
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        }
      ],
      "events": []
    },
    {
      "login": "GinnyJI",
      "name": "Ginny",
      "car": "f1",
      "carLabel": "Formula",
      "color": "#ffbf69",
      "speed": 2,
      "totals": {
        "pr": 0,
        "issue": 0,
        "review": 0,
        "points": 0,
        "distance": 0
      },
      "daily": [
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        }
      ],
      "events": []
    },
    {
      "login": "himanigulati01",
      "name": "Himani",
      "car": "muscle",
      "carLabel": "Muscle",
      "color": "#22d3a5",
      "speed": 1,
      "totals": {
        "pr": 0,
        "issue": 0,
        "review": 0,
        "points": 0,
        "distance": 0
      },
      "daily": [
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        },
        {
          "pr": 0,
          "issue": 0,
          "review": 0,
          "points": 0
        }
      ],
      "events": []
    }
  ]
};
